
#:include debug.kv

<StrategyGame>:
    main_map: _main_map
    BoxLayout:
        orientation: 'horizontal'
        GridLayout:
            id: _main_map
            cols: 10
            size_hint: .75, 1
        BoxLayout:
            orientation: 'vertical'
            size_hint: .25, 1
            DebugLabel:
                text: 'status'
                size_hint: 1, .66
            DebugLabel:
                text: 'mini-map'
                size_hint: 1, .33
